version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/locomoco
    overwrite: yes
permissions:
  - object: /
    owner: root
    group: root
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 120
      runas: root
