version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/locomoco
    overwrite: yes
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 777
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 120
      runas: ubuntu
