name: Java CI with Gradle

on:
  push:
    branches: ["develop"]
  pull_request: 
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create application.yml
      run: printf "%s" "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

    - name: Create directory test resources
      run: mkdir ./src/test/resources

    - name: Create test application.yml
      run: printf "%s" "${{ secrets.TEST_APPLICATION_YML }}" > ./src/test/resources/application.yml

    - name: Create mysql test data
      run: printf "%s" "${{ secrets.MYSQL_TEST_DATA }}" > ./src/main/resources/data.sql
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a

    - name: Setup mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        mysql database: 'locomoco_db_test'
        mysql user: ${{ secrets.MYSQL_USER }}
        mysql password: ${{ secrets.MYSQL_PASSWORD }}

    - name: Restore database from data
      run: |
        mysql -h 127.0.0.1 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} locomoco_db_test < data.sql
    
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
