name: App install and start

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Run actions/setup-java@v2
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'  # JDK 배포자를 선택합니다.
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: 'success'

      - name: Stop old server (ignore error)
        run: |
          killall -9 java || true

      - name: Remove old server directory (ignore error)
        run: |
          rm -rf ~/source || true

      - name: Build Spring application
        run: |
          ./gradlew clean build -x test

      - name: Copy new server to ~/source
        run: |
          mkdir -p ~/source
          cp -R ~/Locomoco_BE/build/libs/locomoco-server-0.0.1-SNAPSHOT.jar ~/source # JAR 파일의 경로를 확인하여 수정

      - name: Run new server (in background)
        run: |
          nohup java -jar ~/source/locomoco-server-0.0.1-SNAPSHOT.jar </dev/null >/dev/null 2>&1 &
