name: App install and start

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # 사용 가능한 Java 버전으로 변경

      - name: Stop old server (ignore error)
        run: |
          killall -9 java || true

      - name: Remove old server directory (ignore error)
        run: |
          rm -rf ~/source || true

      - name: Build Spring application
        run: |
          ./gradlew build

      - name: Copy new server to ~/source
        run: |
          mkdir -p ~/source
          cp -R ./build/libs/*.jar ~/source/locomoco-server-0.0.1-SNAPSHOT.jar # JAR 파일의 경로를 확인하여 수정

      - name: Run new server (in background)
        run: |
          cd ~/source
          nohup java -jar locomoco-server-0.0.1-SNAPSHOT.jar </dev/null >/dev/null 2>&1 &
